spring:
  application:
    name: byteDanceProject01
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.229.44:3306/bytedanceproject?useSSL=false&serverTimezone=UTC
    username:
    password:
  redis:
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    virtual-host: /
    host:
    port:
    username:
    password: