---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by hewei.
--- DateTime: 2022/10/21 14:33
---

local ticketId = ARGV[1]
local userId = ARGV[2]
local orderKey = 'ticket:order:' ..ticketId
local stockKey = 'ticket:stock:' ..ticketId

if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end
if (redis.call('sismember', orderKey, userId) == 1) then
    return 2
end
redis.call('incrby', stockKey, -1)
redis.call('sadd', orderKey, userId)
return 0;